notifications:
  email: false

language: node_js

node_js:
- 12

before_install:
  -  echo "DATABASE_URI=$DATABASE_URI" > ./.env
  -  echo "SESSION_SECRET=$SESSION_SECRET" >> ./.env
  -  echo "API_SECRET=$API_SECRET" >> ./.env
  -  echo "TITLE=$TITLE" >> ./.env
  -  echo "FOOTER_TITLE=$FOOTER_TITLE" >> ./.env
  -  echo "FILE_CHECK=$FILE_CHECK" >> ./.env
  -  echo "CREDIT=$CREDIT" >> ./.env
  -  echo "SHOW_VERSION=$SHOW_VERSION" >> ./.env
  -  echo "SIGNUPS=$SIGNUPS" >> ./.env
  -  echo "SIGNUP_TERMS=$SIGNUP_TERMS" >> ./.env

after_script:
  - rm ./.env

install:
- npm install

script:
- npm run test
