language: node_js
node_js:
- 12
env:
  global:
  - SESSION_SECRET=thisistesting
  - API_SECRET=thisistesting
  - TITLE=Share
  - FOOTER_TITLE=MrDemonWolf
  - DESC="Advanced uploader with web front-end for images,files,and text. Built with
    ShareX in mind. Licensed under MIT and is free to use."
  - FILE_CHECK=true
  - CREDIT=true
  - SHOW_VERSION=true
  - SIGNUPS=true
  - SIGNUP_TERMS=true
  - secure: a0n5vSXrw7/JbPt1EAOloBtQhiJZJElircHvJbcg2IWCurnrB7Sv5ND7VbaLZGHeHdIPpJmATQixL/l0jwoy7NnomuUOBA0ZHEC6Ufa9bkErv6ZEhQPEFtfJ9/iFKXZMpsQcacJhfvT3Qqy267P+xsZUaJO8HfYtb/z2JmL31aCLXGgqYxVa+SGX7S4CV5eGJT8wS0ZgjD4D9eTbEb+/pEylKmC4Z/BTwcX1j6VksT7i6x4istNoYnjkjQJjXtDQa8hjKlHAJ8kwDys9URuz4iLTy+uGuROCCwl+h5j7Aw4f91QjFqddYXEoKYXBbhEsPMNHfmFpfIvePkRUEW2nWzW+x5EO0KXpcxYI/iO5a5MO/W/Qxb1bFKAWXbgSjsE7TSj47Mh6gWepfZFMbwWdGSZ35oNXo2A92DaZf7K2niTNjeTTkG7ffx0599hZUiE49epuRYa67yl/Ooduw4Jc+xpJWHD7ck2GViv/dFZcjuUKoPiAK8PgkLQ4/jCQ+JuAFB+cSGtx3sg2A4IWMGt9ChyHL6Ncmp44iW+izueo+ue6cJ6A0bgRlmxzadigYi1KbXsx8n/Fa3RrX3MC0SIlroRZuhGhC6/SsuyFJuTVIV/6P2j2NVq2GCv65SWw1iQtWbmYU3Iw/R0KAdqyq3vf2inBLLRu2OyE+bHwFN1anQU=
install:
- npm install
script:
- npm run test
