language: node_js
node_js:
- node
- lts/*
env:
  - "SESSION_SECRET=thisistesting"
  - "API_SECRET=thisistesting"
  - "TITLE=Share"
  - "FOOTER_TITLE=MrDemonWolf"
  - "DESC=Advanced uploader with web front-end for images,files,and text. Built with"
    "ShareX in mind. Licensed under MIT and is free to use."
  - "FILE_CHECK=true"
  - "CREDIT=true"
  - "SHOW_VERSION=true"
  - "SIGNUPS=true"
  - "SIGNUP_TERMS=true"
  global:
    secure: L3ha9a56Obj6w1QVR21/SobvpODALj7cCThRC/4RcByHY+gcxtyRpcCU+TxMb73QbYlRkWXKCf8CydPCwCX8IDQSvAkmCFlbKnYt08TJYcVhQJlm9uP6aOHYDPohfnEUna3+9qQxc4ArtHUBxuWa9kbu1h4pa9ide0HtUy4nauxllIrn5q1JWWTHwaGcURC4JnB13E1G1YQhtrzvml8fp/QU2Wc6xeYZLude3ay/ErbrNXtETL+Y51sWyVKzVBVffrK3v8pnhyB4rq94PypmEIrNKiZBUcWo9EhPVfrBipPHOZV2L4xHUms9zrIGPAkCUcn29Aj3sgyZETjgvFZ0vz6fWBpjPn4m5D3WvYe5Jv4UvgprwOsF8tTnjWUF2Jyn2e49goX/o8iUWTGf3EKLjVK2zz+4AuHNhW1JTDLFOxbuIwS2CQ5rrPUHmJ+8rtm6ZrySo2WbbwLz2m0ZLr5Y2PnPJ0RTBk3tuwILfE7QCZyqfuX1J+wHplhhedYcirKksc19QSngRiqW1Ii7yD8Br3evO+6HGk2vpBSAFaSJDotIsvaPt/JBzYqEZy05AN21/EleazluTBp0aTF3guznuZXKP+EQ3RjXs3pStcmZPi7tKiACGfOSqJtKR5E2e+Np+LQDBEV41qVbn7C5JTTiVB4T3VJhla4LWFkW5hkcthA=
install:
  - npm install
script:
  - npm run test
