notifications:
  email: false

language: node_js

node_js:
  - 12
cache: npm

services: mongodb

git:
  quiet: true

addons:
  hosts:
    - mrdemonwolf.me
    - mrdemonwolf.local

# branches:
#   only:
#     - master
#     - development

env:
  global:
    - DATABASE_URI=mongodb://localhost:27017/share
    - SESSION_SECRET=thisistesting
    - JWT_SECRET=thisistesting
    - TITLE=Share
    - FOOTER_TITLE=MrDemonWolf
    - DESC="Advanced uploader with web front-end for images,files,and text. Built with
      ShareX in mind. Licensed under MIT and is free to use."
    - FILE_CHECK=true
    - CREDIT=true
    - SHOW_VERSION=true
    - SIGNUPS=true
    - SIGNUP_TERMS=true

before_install:
  - echo "DATABASE_URI=$DATABASE_URI" > ./.env
  - echo "SESSION_SECRET=$SESSION_SECRET" >> ./.env
  - echo "JWT_SECRET=$JWT_SECRET" >> ./.env
  - echo "TITLE=$TITLE" >> ./.env
  - echo "FOOTER_TITLE=$FOOTER_TITLE" >> ./.env
  - echo "FILE_CHECK=$FILE_CHECK" >> ./.env
  - echo "CREDIT=$CREDIT" >> ./.env
  - echo "SHOW_VERSION=$SHOW_VERSION" >> ./.env
  - echo "SIGNUPS=$SIGNUPS" >> ./.env
  - echo "SIGNUP_TERMS=$SIGNUP_TERMS" >> ./.env
after_script:
  - rm ./.env

install:
  - npm install

script:
  - npm run test
