notifications:
  email: false
language: node_js
node_js:
- 12
env:
  global:
  - secure: 6QL2VCzhYpHXXxDKeIbXgnIjHlo0MtWCyBgdRxeaChxBpUGBFxLwKmj3br7HDgpkDK/SvrjFmrqqyeG/n5ZVQHQjMb4JbuSWfV+bvE1LLJJvUPgcvleeb7ABBHmtQ1IKEYf9oohO6tDpFqDACKd8z3B4+DelmP01JmHhO7wYlYIam2Djr1VYeh58WtbjzFsJPR3hywie/Shl1b+N7a30gOmjBdldxnO77K96niy2beI5Eiqk0Frr6fLW6MsHe2YGWTUaXPoH5Vpi/85VAfVHFw64IjN9RjNw2T0wDSQIBmxudjfqmY43eyMl9ifGjs9eHoG9hiJ3cAF0bPfQBY7YcyNZi6CLLqpIPSNEQ54kHo4znroDL+cNcCHDM20Eh2kAbihgMTifwb2Q+K/1SGaJnkQp+dRRBzrJ6eZUyL1cLdCAAbX+H2VCT8GBNHrUU21Lzvxc8kTDyLmkRdXhOx0bI8Ctjraz2jUAujORXrw5P3tK0VpmFaz5a1AkrpWxFenJ1orxqe9oe7LsupRm3sCUWquPE7MraO8uodSrvEsa/LMY+nD8uksV+HPoCjTXAh0CpUl5L1LjahLQkMTRKIK3JAqz9zehbvGvSwm48IgNLxoLFjKa+a4HzOm+N4CvNoSVhB4HHoNOOgjQvH54GR1Lv0nRimc1tpgQD6UwCGWioq0=
  - SESSION_SECRET=thisistesting
  - API_SECRET=thisistesting
  - TITLE=Share
  - FOOTER_TITLE=MrDemonWolf
  - DESC="Advanced uploader with web front-end for images,files,and text. Built with
    ShareX in mind. Licensed under MIT and is free to use."
  - FILE_CHECK=true
  - CREDIT=true
  - SHOW_VERSION=true
  - SIGNUPS=true
  - SIGNUP_TERMS=true
before_install:
- echo "DATABASE_URI=$DATABASE_URI" > ./.env
- echo "SESSION_SECRET=$SESSION_SECRET" >> ./.env
- echo "API_SECRET=$API_SECRET" >> ./.env
- echo "TITLE=$TITLE" >> ./.env
- echo "FOOTER_TITLE=$FOOTER_TITLE" >> ./.env
- echo "FILE_CHECK=$FILE_CHECK" >> ./.env
- echo "CREDIT=$CREDIT" >> ./.env
- echo "SHOW_VERSION=$SHOW_VERSION" >> ./.env
- echo "SIGNUPS=$SIGNUPS" >> ./.env
- echo "SIGNUP_TERMS=$SIGNUP_TERMS" >> ./.env
after_script:
- rm ./.env
install:
- npm install
script:
- npm run test
