notifications:
  email: false

language: node_js

node_js:
- 12
env:
  global:
  # - secure: "oTqdGd6bZxDJiucA5xSOYcsNN/msQGbEKbM7pn8hyDBPn/8wUZ/MXE82ySrmFkS7xw9ig7fUi5X/06bhubRfC0G1t5pecLZWjCXtEfWVTxnGrorBwNk0IoXq+q7lLW9b+44Vcqh+JQYDU0mIGqbETNoK+/ayf0OjV+9OLW966FYLdFvDaMp5hf8IG/oGQLbV0JY+y3Wg/hO2Gce0armHGN5qz2Hz4Jhss6vI52O0KDGYgXeKsGNfnQHGnL9Cx1v4FteTK09iwW0a3EB6kPdJ8lbpMKqwxxwyH08mBH+yVlSZniDxy3b7Brry1ZDe3r8OdS8WVsvznM6W//LKnXj5GnJAlMYRUufryOA1mKHFWtddhhF5IEptG7JOBjj8gBhi4P2YvidqzXC47FCMTXZD899zuMggx+RuzQ+ItLAW3HYfJ0//ayaSsL45MRQ0e/qjlirHlfJjdgOSShPTssDmqgYePQSTHGnDV87ZkgCgepjDyyvixQKnsZsXSLHNvMyhbQAJWfR6RXNtC8p7GP4gj2t/CzBY6MAIXWBQFJVywd+ZJi7TC0b40RExjSaW7jBrrjqm/r0SB2uKSlhlyKJEHlW53nWNVF7rv17D7U1l5koU/J5bHd20WxrbeGBd6UIgCnm/mwnsUKKvwGUm0wp+F6AXFZyjUeYkkFFxqz2n+1A="
  - SESSION_SECRET=thisistesting
  - API_SECRET=thisistesting
  - TITLE=Share
  - FOOTER_TITLE=MrDemonWolf
  - DESC="Advanced uploader with web front-end for images,files,and text. Built with
    ShareX in mind. Licensed under MIT and is free to use."
  - FILE_CHECK=true
  - CREDIT=true
  - SHOW_VERSION=true
  - SIGNUPS=true
  - SIGNUP_TERMS=true

# before_install:
  # -  echo $DATABASE_URI > ./.env
  # -  echo $SESSION_SECRET >> ./.env
  # -  echo $API_SECRET >> ./.env
  # -  echo $TITLE >> ./.env
  # -  echo $FOOTER_TITLE >> ./.env
  # -  echo $FILE_CHECK >> ./.env
  # -  echo $CREDIT >> ./.env
  # -  echo $SHOW_VERSION >> ./.env
  # -  echo $SIGNUPS >> ./.env
  # -  echo $SIGNUP_TERMS >> ./.env

after_script:
  - rm ./.env

install:
- npm install
script:
- npm run test
